version: '1'

# Whether to receive email notifications or not
notify_email: True

# put your design source file(s) in the design folder
# write down add design file names to be synthesized
design_files: 
  - rv32_CPU.v

top_level_module: rv32_CPU

# available libraries on https://flow.theopenroadproject.org
# select from the below options
# [osu045.lib]
library: osu045.lib

flow:
  - logic_synthesis
  - floor_planning
  - placement
  - clock_tree_synthesis
  - routing

# customize your flow using the parameters below
stages:
  logic_synthesis:
    tool: yosys
    params:
      - p1: false
      - p2: 12
  floor_planning:
    tool: tw
    params:
      - p1: false
      - p2: 'default'
  placement:
    tool: replace
    params:
      - p1: true
      - p2: 'default'
  clock_tree_synthesis:
    tool: tw
    params:
      - p1: false
      - p2: true
  routing:
    tool: tw
    params:
      - p1: 'default'
      - p2: 'default'
