version: '1'

# put your design source file(s) in the design folder
# change this to your design file name
design_file: design/my_design.v

# available libraries on https://flow.theopenroadproject.org
# select from the below options
# [14nm.genlib, 17nm.genlib, 22nm.genlib]
library: 14nm.genlib

flow:
  - ls
  - fp
  - pl
  - rt
  - cts

# customize your flow using the parameters below
stages:
  - ls
    - tool: yosys
    - params:
      - p1: false
      - p2: 12
  - fp
    - tool: sim
    - params:
      - p1: false
      - p2: 'default'
  - pl
    - tool: replace
    - params:
      - p1: true
      - p2: 'default'
  - rt
    - tool: sim
    - params:
      - p1: 'default'
      - p2: 'default'
  - cts
    - tool: sim
    - params:
      - p1: false
      - p2: true
